llm:
  groq: 
    provider: "groq"
    model_name: "openai/gpt-oss-20b"
  gemini:
    provider: "gemini"
    model_name: "gemini-2.5-flash"
  gemini_lite:
    provider: "gemini_lite"
    model_name: "gemini-2.5-flash-lite"

embedding_model: 
  openai: 
    provider: "openai"
    model_name: "text-embedding-3-small"
  huggingface:
    provider: "huggingface"
    model_name: "mixedbread-ai/mxbai-embed-large-v1"

    
